name: Deploy Node.js Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Set your desired Python version

      - name: Install Python dependencies
        run: |
          python -m venv myenv
          source myenv/bin/activate
          pip install -r script/requirements.txt

      - name: Install Node.js dependencies
        run: npm install

      - name: Run Python script
        run: |
          source myenv/bin/activate
          python script/index.py  # Your Python script to run

      - name: Deploy
        run: |
          # Replace with your deployment command
          echo "Deploying to production"
